#!/bin/bash

#set -e  # Exit immediately if a command exits with a non-zero status


#set -u # Treat unset/uninitalised variables as an error and exit immediately
#echo "The value of the variable is: $UNSET_VAR"  # This will cause an error if -u is set

#set -x prints each command to the terminal before executing it
#  set -x

#  echo "This is a test script."
#  X=10
#  Y=20
#  Z=$((X + Y))
#  echo "The value of $X and $Y is: $Z"
#set +x # Disable debugging mode

# set -eux # Enable strict error handling, exit on error, and print commands before executing them
# echo "This is a test script."
# X=10
# echo "The value of the variable X is: $X"
# nonexistentcommand

#set -o nounset # Treat unset variables as an error
#set -o errexit # Exit immediately if a command exits with a non-zero status
# set -o pipefail # Exit with the status of the last command in the pipeline that failed